version: '3'
services:
  codepeer:
    image: cdpimg
    container_name: codepeer_serve
    build:
      context: codepeer
      args:
        project: sdc.gpr
    volumes:
      - ./codepeer/tutorial:/my_project
    expose:
      - 8080
    entrypoint: >
      bash -c "codepeer -P sdc.gpr -XReport=HTML
      && codepeer -P sdc.gpr -XReport=HTML --web-server --ide-server --port=8080"
  nginx:
    image: nginx:latest
    ports:
      - 80:80
#      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
